// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOMuCXNVUGuaNao0KsYTZWcYxiFxRyuRc',
    appId: '1:1034330779736:web:0f23bacad47332e51ada2d',
    messagingSenderId: '1034330779736',
    projectId: 'login-b6988',
    authDomain: 'login-b6988.firebaseapp.com',
    storageBucket: 'login-b6988.firebasestorage.app',
    measurementId: 'G-24KD6B6LRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFVsFzZbbDddaTxgVwn6-70WXKNwluOJ0',
    appId: '1:1034330779736:android:a88f952c899d964f1ada2d',
    messagingSenderId: '1034330779736',
    projectId: 'login-b6988',
    storageBucket: 'login-b6988.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2JKgE1aLnywkNXzWPCKhKD0v0K9O7sC0',
    appId: '1:1034330779736:ios:9024f99b7dcfc7d81ada2d',
    messagingSenderId: '1034330779736',
    projectId: 'login-b6988',
    storageBucket: 'login-b6988.firebasestorage.app',
    iosBundleId: 'com.example.advanced',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2JKgE1aLnywkNXzWPCKhKD0v0K9O7sC0',
    appId: '1:1034330779736:ios:9024f99b7dcfc7d81ada2d',
    messagingSenderId: '1034330779736',
    projectId: 'login-b6988',
    storageBucket: 'login-b6988.firebasestorage.app',
    iosBundleId: 'com.example.advanced',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOMuCXNVUGuaNao0KsYTZWcYxiFxRyuRc',
    appId: '1:1034330779736:web:b19bba7803ec25d91ada2d',
    messagingSenderId: '1034330779736',
    projectId: 'login-b6988',
    authDomain: 'login-b6988.firebaseapp.com',
    storageBucket: 'login-b6988.firebasestorage.app',
    measurementId: 'G-8HXEL66N72',
  );

}